services:
  - type: web
    name: rentacar-app
    env: java
    runtime: java17
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: chmod +x start.sh && ./start.sh
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_TOOL_OPTIONS
        value: "-Xmx512m"
    autoDeploy: true
